# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoenhance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='django_images', verbose_name='img')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='django_images', verbose_name='img')),
                ('name', models.CharField(default='something', max_length=100, primary_key=True, serialize=False, verbose_name='name')),
                ('url', models.CharField(default='something', max_length=100, verbose_name='url')),
            ],
        ),
    ]
