# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0002_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='brightness',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='contrast',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
