# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0002_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='url',
        ),
        migrations.AddField(
            model_name='layout',
            name='path',
            field=models.CharField(default='something', max_length=100, verbose_name='path'),
        ),
    ]
