# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0003_auto_20160222_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='path',
        ),
        migrations.AlterField(
            model_name='layout',
            name='image',
            field=models.ImageField(default='django_images/None/no-img.jpg', upload_to='django_images', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='original_image',
            field=models.ImageField(default='django_images/None/no-img.jpg', upload_to='django_images', verbose_name='img'),
        ),
    ]
