# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0003_auto_20160331_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='autoenhance',
            field=models.BooleanField(default=False),
        ),
    ]
