# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0004_auto_20160222_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='layout',
            name='original_image',
            field=models.ImageField(blank=True, upload_to='django_images', verbose_name='original_image'),
        ),
    ]
