# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoenhance', '0005_auto_20160222_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='original_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
